#ifndef TASK_MSG_NAME_USER_DEF_H_
#define TASK_MSG_NAME_USER_DEF_H_

#define TASK_MSG_NAME_USER_DEF
enum task_msg_name{
    TASK_MSG_OS_REDAY = 0,
    TASK_MSG_NET_REDAY,
    TASK_MSG_NET_REDAY1,
    TASK_MSG_NET_REDAY2,
    TASK_MSG_NET_REDAY3,
    TASK_MSG_NET_REDAY4,
    TASK_MSG_NET_REDAY5,
    TASK_MSG_COUNT
};
#endif
